name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'DEPLOY.md'
      - '.gitignore'
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_SSH_KEY }}
        port: ${{ secrets.PI_PORT }}
        script: |
          cd /home/pi/RiotBot
          git pull origin main
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d

    - name: Verify deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_SSH_KEY }}
        port: ${{ secrets.PI_PORT }}
        script: |
          echo "Checking if container is running..."
          docker ps | grep riotbot
          echo ""
          echo "Recent logs:"
          docker logs riotbot --tail 20